# Site settings
title: Things I've Learned Along The Way
header-img: img/home-bg.png
email: acodercalledcole@gmail.com
copyright_name: brettCole
description: > # this means to ignore newlines until "baseurl:"
  The Good, The Bad and The Ugly
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  brettCole
learn_profile: brettCole
email_username: acodercalledcole@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
